# Generated by Django 3.1.3 on 2020-11-19 12:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.TextField()),
                ('time', models.DurationField()),
                ('starttime', models.DateTimeField(default=django.utils.timezone.now)),
                ('pfield', models.CharField(max_length=20)),
                ('branch_restriction', models.BooleanField(default=False)),
                ('number_of_people', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rname', models.TextField()),
                ('rfield', models.CharField(max_length=20)),
                ('rnumber_of_people', models.IntegerField()),
                ('duration', models.DurationField()),
                ('research_start_time', models.DateTimeField()),
                ('dept_restriction', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=20)),
                ('contact', models.BigIntegerField()),
                ('tdept', models.CharField(max_length=20)),
                ('field_of_specialization', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=15)),
                ('contact', models.BigIntegerField()),
                ('field_of_interest', models.CharField(max_length=20)),
                ('sem', models.IntegerField()),
                ('sdept', models.CharField(max_length=20)),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.research')),
            ],
        ),
        migrations.CreateModel(
            name='Research_Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.research')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.project')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.project')),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.student')),
            ],
        ),
    ]
