# Generated by Django 3.1.3 on 2020-11-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='field_of_specialization',
            field=models.CharField(max_length=20),
        ),
    ]
