# Generated by Django 3.1.3 on 2020-11-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_auto_20201119_1823'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project_student',
            unique_together={('pid', 'usn')},
        ),
        migrations.AlterUniqueTogether(
            name='project_teacher',
            unique_together={('tid', 'pid')},
        ),
        migrations.AlterUniqueTogether(
            name='research_teacher',
            unique_together={('rid', 'tid')},
        ),
    ]
