# Generated by Django 3.1.3 on 2020-11-19 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_auto_20201119_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connect.research'),
        ),
    ]
