# Generated by Django 3.1.3 on 2020-11-19 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_auto_20201119_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='connect.research'),
        ),
    ]
