# Generated by Django 3.1.3 on 2020-11-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_auto_20201120_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projshortdesc',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='research',
            name='rescshortdesc',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='pname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='research',
            name='rname',
            field=models.CharField(max_length=20),
        ),
    ]
