# Generated by Django 3.1.3 on 2020-11-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0007_auto_20201121_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='people_requested',
            field=models.ManyToManyField(default=None, to='connect.Student'),
        ),
    ]
