# Generated by Django 3.1.3 on 2020-11-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0008_research_people_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='people_requested',
            field=models.ManyToManyField(default=None, to='connect.Student'),
        ),
    ]
