# Generated by Django 3.1.3 on 2020-11-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0009_project_people_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='people_requested',
        ),
        migrations.RemoveField(
            model_name='research',
            name='people_requested',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='connect123', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='connect123', max_length=20),
        ),
    ]
