# Generated by Django 3.1.3 on 2020-11-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0010_auto_20201124_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projshortdesc',
            field=models.TextField(default=None),
        ),
    ]
