# Generated by Django 3.1.3 on 2020-11-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0011_auto_20201125_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_branch',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='research',
            name='research_department',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
