# Generated by Django 3.1.3 on 2020-11-28 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0012_auto_20201125_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='field_of_interest',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='field_of_specialization',
        ),
    ]
