# Generated by Django 3.1.3 on 2020-11-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0013_auto_20201129_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contact',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
