# Generated by Django 3.1.3 on 2020-12-08 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0015_auto_20201208_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='starttime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='research',
            name='research_start_time',
            field=models.DateField(),
        ),
    ]
