# Generated by Django 3.1.3 on 2020-12-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0016_auto_20201208_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_student',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='connect.project'),
        ),
        migrations.AlterField(
            model_name='project_student',
            name='usn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='connect.student'),
        ),
        migrations.AlterField(
            model_name='project_teacher',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='connect.project'),
        ),
        migrations.AlterField(
            model_name='project_teacher',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='connect.teacher'),
        ),
        migrations.AlterField(
            model_name='research_teacher',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='connect.research'),
        ),
        migrations.AlterField(
            model_name='research_teacher',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='connect.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='connect.research'),
        ),
    ]
