# Generated by Django 3.1.3 on 2020-12-09 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0018_auto_20201209_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_student',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.project'),
        ),
        migrations.AlterField(
            model_name='project_student',
            name='usn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='connect.student'),
        ),
        migrations.AlterField(
            model_name='research_teacher',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.research'),
        ),
        migrations.AlterField(
            model_name='research_teacher',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='connect.teacher'),
        ),
    ]
